import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

const __dirname = dirname(fileURLToPath(import.meta.url))

// Ship `fixtures/` alongside the Vite build output. Production requests for
// `/map-data.json` are served from the S3 copy generated by CI; if that 404s
// (fork deploy without DB access, or a transient S3 issue), `src/lib/api.ts`
// falls back to `/fixtures/map-data.json`.
const copyFixturesToDist: Plugin = {
  name: 'copy-fixtures-to-dist',
  async writeBundle() {
    const { cp } = await import('node:fs/promises')
    await cp(resolve(__dirname, 'fixtures'), resolve(__dirname, 'dist/fixtures'), {
      recursive: true,
      force: true,
    })
  },
}

export default defineConfig({
  appType: 'mpa',
  plugins: [tailwindcss(), react(), copyFixturesToDist],
  build: {
    outDir: 'dist',
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        contribute: resolve(__dirname, 'contribute.html'),
        map: resolve(__dirname, 'map.html'),
        about: resolve(__dirname, 'about.html'),
        admin: resolve(__dirname, 'admin.html'),
        theoryofchange: resolve(__dirname, 'theoryofchange.html'),
        workshop: resolve(__dirname, 'workshop/index.html'),
        insights: resolve(__dirname, 'insights.html'),
      },
    },
  },
  server: {
    proxy: {
      '/api': {
        target: 'http://localhost:3000',
        changeOrigin: true,
      },
    },
  },
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./src/test-setup.ts'],
    exclude: ['.aws-sam/**', 'node_modules/**'],
  },
})
