export const FIELD_OPTIONS = {
  personCategory: [
    'Executive',
    'Researcher',
    'Policymaker',
    'Investor',
    'Organizer',
    'Journalist',
    'Academic',
    'Cultural figure',
  ],
  orgCategory: [
    'Frontier Lab',
    'AI Safety/Alignment',
    'Think Tank/Policy Org',
    'Government/Agency',
    'Academic',
    'VC/Capital/Philanthropy',
    'Labor/Civil Society',
    'Ethics/Bias/Rights',
    'Media/Journalism',
    'Political Campaign/PAC',
    'Infrastructure & Compute',
    'Deployers & Platforms',
  ],
  regulatoryStance: ['Accelerate', 'Light-touch', 'Moderate', 'Cautious', 'Mixed/unclear'],
  agiTimeline: ['<2 years', '2-5 years', '5-10 years', '10-20 years', '20+ years', 'Never', 'Mixed/unclear'],
  aiRisk: ['Existential', 'High', 'Moderate', 'Low', 'Minimal', 'Mixed/unclear'],
  threatModels: [
    'Power concentration',
    'Misuse',
    'Accidents/misalignment',
    'Erosion of epistemics',
    'Labor/economic',
    'Surveillance/privacy',
    'Bias/discrimination',
    'Copyright/IP',
  ],
  evidenceSources: ['Direct quote', 'Published writing', 'Public statement', 'Inferred from actions'],
  fundingModel: ['Grants', 'Contracts', 'VC', 'Donations', 'Government', 'Revenue', 'Endowment'],
  edgeTypes: [
    'employed_by',
    'founded',
    'advises',
    'board_member',
    'invested_in',
    'co_founded_with',
    'collaborator',
    'mentor_of',
    'mentored_by',
    'former_colleague',
    'critic_of',
    'supporter_of',
    'subsidiary_of',
    'funded_by',
    'partner_of',
    'spun_out_from',
    'affiliated',
  ],
  errorTypesField: ['HALLUCINATED', 'MISCLASSIFIED', 'OUTDATED', 'WRONG_VALUE', 'NOT_AI_RELATED', 'TOO_GENERIC'],
  errorTypesClaim: [
    'HALLUCINATED',
    'MISQUOTED',
    'MISCLASSIFIED',
    'OUTDATED',
    'WRONG_SCORE',
    'SOURCE_MISSING',
    'NOT_AI_RELATED',
  ],
  errorTypesEdge: ['WRONG_TYPE', 'WRONG_DIRECTION', 'OUTDATED', 'DUPLICATE', 'DOES_NOT_EXIST', 'MISSING_EVIDENCE'],
  errorTypesNotes: ['HALLUCINATED', 'INACCURATE', 'OUTDATED', 'MISSING_CONTEXT', 'WRONG_ATTRIBUTION'],
} as const
