const SECTION = 'mb-8'
const H2 = 'text-xl mb-3'
const H3 = 'text-base font-medium mb-2 mt-4'
const P = 'text-[14px] text-[#333] leading-relaxed mb-3'
const LI = 'text-[14px] text-[#333] leading-relaxed mb-1.5'
const NOTE = 'text-[13px] text-[#555] bg-[#f5f5f0] border border-[#e0ddd5] rounded p-3 mb-3'
const STEP = 'text-[14px] text-[#333] leading-relaxed mb-2 pl-4 border-l-2 border-[#ddd]'

export function MethodologyGuide({ onClose }: { onClose: () => void }) {
  return (
    <div className="fixed inset-0 z-50 bg-white overflow-y-auto">
      <div className="max-w-[750px] mx-auto px-6 py-8">
        <div className="flex items-center justify-between mb-8">
          <h1 className="text-2xl" style={{ fontFamily: "'EB Garamond', Georgia, serif" }}>
            Verification Guide
          </h1>
          <button
            onClick={onClose}
            className="font-mono text-[11px] uppercase tracking-wider px-3 py-1.5 rounded cursor-pointer border bg-white text-[#555] border-[#ccc] hover:border-[#999] transition-colors"
          >
            Close
          </button>
        </div>

        <section className={SECTION}>
          <h2 className={H2} style={{ fontFamily: "'EB Garamond', Georgia, serif" }}>
            Background
          </h2>
          <p className={P}>
            Mapping AI tracks people, organizations, and resources in the U.S. AI policy landscape. The public site is
            at{' '}
            <a
              href="https://mapping-ai.org"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-600 hover:underline"
            >
              mapping-ai.org
            </a>
            . Most of the entity data was generated by automated scripts that searched the web, extracted quotes from
            source documents, and assigned belief scores. The automation is imperfect. Some claims are fabricated,
            misattributed, or drawn from unreliable sources. Verification means checking what the automation got right
            and flagging what it got wrong.
          </p>
        </section>

        <section className={SECTION}>
          <h2 className={H2} style={{ fontFamily: "'EB Garamond', Georgia, serif" }}>
            What to verify
          </h2>

          <h3 className={H3}>Structured fields</h3>
          <p className={P}>
            Basic facts about the entity: category, regulatory stance, AGI timeline belief, AI risk level, threat
            models, funding model, website, title/role, primary organization, and location. Each field either has a
            value or shows "Not set." Check whether the value looks right. If the entity is categorized as "Academic"
            but is actually a think tank, flag it. If a field is empty but you can determine the answer, flag it and
            provide the correct value.
          </p>

          <h3 className={H3}>Claims</h3>
          <p className={P}>
            Claims are sourced assertions about an entity's beliefs. Each has a belief dimension (regulatory stance, AGI
            timeline, or AI risk level), a value/score, a direct quote, and a source link. Verify three things for each
            claim:
          </p>
          <ol className="list-decimal pl-6 mb-3">
            <li className={LI}>
              <strong>Source accessible:</strong> Can you open the URL? Some links are dead, paywalled, or redirect
              elsewhere.
            </li>
            <li className={LI}>
              <strong>Quote found:</strong> Does the citation actually appear on the page? Copy the quote text (use the
              "copy" button), open the source, and Ctrl+F for it.
            </li>
            <li className={LI}>
              <strong>Conclusion supported:</strong> Does the quote support the assigned stance/score? Read the quote in
              context on the source page and assess whether the label is reasonable.
            </li>
          </ol>
          <div className={NOTE}>
            Some entities have no claims. Their belief fields come from crowdsourced submissions instead of sourced
            claims. You can still verify the structured fields but there won't be source citations to check.
          </div>

          <h3 className={H3}>Edges</h3>
          <p className={P}>
            Edges are relationships between entities: employment, board membership, funding, advisory roles,
            partnerships. Each has a type and may have evidence records with source citations. Check whether the
            relationship exists and whether the type is correct. Someone listed as "employed by" might actually be an
            advisor. Verify any cited evidence the same way you verify claims.
          </p>

          <h3 className={H3}>Notes</h3>
          <p className={P}>
            Free-text summaries of an entity's positions, history, or relationships. Often generated by enrichment
            scripts. May contain inaccuracies, outdated information, or unsupported assertions.
          </p>
        </section>

        <section className={SECTION}>
          <h2 className={H2} style={{ fontFamily: "'EB Garamond', Georgia, serif" }}>
            Workflow
          </h2>

          <h3 className={H3}>1. Pick an entity</h3>
          <p className={STEP}>
            The left sidebar lists entities by priority. Organizations with the most connections appear first because
            errors on highly connected entities affect more of the map. Click any entity to load it.
          </p>

          <h3 className={H3}>2. Review structured fields</h3>
          <p className={STEP}>
            Scan each field. Click "Flag" on anything wrong or missing. Select the error type, pick the correct value
            from the dropdown if applicable, and add notes.
          </p>

          <h3 className={H3}>3. Verify claims</h3>
          <p className={STEP}>
            Open the source link (opens in a new tab). Check each of the three verification boxes as you go. Copy the
            citation text and search the source page for it. If everything checks out, click "Correct." Otherwise click
            "Needs Correction." The "View source excerpt" toggle shows what the extraction system saw at the time it
            processed the source, which can help when the live page has changed.
          </p>

          <h3 className={H3}>4. Check edges</h3>
          <p className={STEP}>
            Review edge types and evidence. Verify source citations the same way you verify claims. Flag wrong types or
            fabricated relationships.
          </p>

          <h3 className={H3}>5. Review notes</h3>
          <p className={STEP}>
            Read through the notes. Flag anything fabricated, inaccurate, or outdated. When flagging, explain what is
            wrong and what the correct information is.
          </p>

          <h3 className={H3}>6. Mark complete</h3>
          <p className={STEP}>
            Click "Mark Complete" at the bottom. This records the review and the time spent. Corrections flagged along
            the way are already saved. If you can't properly verify an entity (all sources paywalled, insufficient
            domain knowledge), click "Can't verify" instead.
          </p>
        </section>

        <section className={SECTION}>
          <h2 className={H2} style={{ fontFamily: "'EB Garamond', Georgia, serif" }}>
            Error types
          </h2>
          <p className={P}>
            Error type pills are specific to what you're correcting. You can select multiple and add a custom type.
          </p>

          <h3 className={H3}>Fields</h3>
          <ul className="list-disc pl-6 mb-3">
            <li className={LI}>
              <strong>HALLUCINATED:</strong> Value has no basis in reality.
            </li>
            <li className={LI}>
              <strong>MISCLASSIFIED:</strong> Real information, wrong label.
            </li>
            <li className={LI}>
              <strong>OUTDATED:</strong> Was correct but is no longer current.
            </li>
            <li className={LI}>
              <strong>WRONG VALUE:</strong> Right field type, wrong specific value.
            </li>
            <li className={LI}>
              <strong>NOT AI RELATED:</strong> Entity doesn't belong in the dataset.
            </li>
            <li className={LI}>
              <strong>TOO GENERIC:</strong> Entity is too broad to be useful (e.g., "U.S. Senate").
            </li>
          </ul>

          <h3 className={H3}>Claims</h3>
          <ul className="list-disc pl-6 mb-3">
            <li className={LI}>
              <strong>HALLUCINATED:</strong> Quote doesn't exist on the source page.
            </li>
            <li className={LI}>
              <strong>MISQUOTED:</strong> Quote exists but was altered or taken out of context.
            </li>
            <li className={LI}>
              <strong>MISCLASSIFIED:</strong> Quote is real but the derived stance/score is wrong.
            </li>
            <li className={LI}>
              <strong>WRONG SCORE:</strong> Numeric score doesn't match the label or content.
            </li>
            <li className={LI}>
              <strong>SOURCE MISSING:</strong> URL is dead, paywalled, or redirects.
            </li>
            <li className={LI}>
              <strong>OUTDATED:</strong> Position has since changed.
            </li>
          </ul>

          <h3 className={H3}>Edges</h3>
          <ul className="list-disc pl-6 mb-3">
            <li className={LI}>
              <strong>WRONG TYPE:</strong> Relationship exists but type is wrong.
            </li>
            <li className={LI}>
              <strong>WRONG DIRECTION:</strong> Edge points the wrong way (A funds B, not B funds A).
            </li>
            <li className={LI}>
              <strong>DOES NOT EXIST:</strong> Relationship is fabricated.
            </li>
            <li className={LI}>
              <strong>DUPLICATE:</strong> Duplicates another edge between the same entities.
            </li>
            <li className={LI}>
              <strong>OUTDATED:</strong> Relationship ended.
            </li>
            <li className={LI}>
              <strong>MISSING EVIDENCE:</strong> May be real but has no source to verify.
            </li>
          </ul>

          <h3 className={H3}>Notes</h3>
          <ul className="list-disc pl-6 mb-3">
            <li className={LI}>
              <strong>HALLUCINATED:</strong> Contains fabricated facts or quotes.
            </li>
            <li className={LI}>
              <strong>INACCURATE:</strong> Based on real information but gets details wrong.
            </li>
            <li className={LI}>
              <strong>OUTDATED:</strong> No longer current.
            </li>
            <li className={LI}>
              <strong>MISSING CONTEXT:</strong> Omits information that changes the picture.
            </li>
            <li className={LI}>
              <strong>WRONG ATTRIBUTION:</strong> Attributes something to the wrong entity.
            </li>
          </ul>
        </section>

        <section className={SECTION}>
          <h2 className={H2} style={{ fontFamily: "'EB Garamond', Georgia, serif" }}>
            Reference: categories and field values
          </h2>
          <p className={P}>Click any section below to expand definitions.</p>

          <details className="mb-3 border border-[#e0e0e0] rounded">
            <summary className="px-3 py-2 font-mono text-[12px] font-medium cursor-pointer hover:bg-[#f5f5f5]">
              Person categories
            </summary>
            <div className="px-3 pb-3 text-[13px] text-[#444] space-y-1">
              <p>
                <strong>Executive:</strong> CEO, CTO, VP, or equivalent leadership at an AI-relevant organization.
              </p>
              <p>
                <strong>Researcher:</strong> Publishes technical AI research, whether in industry or academia.
              </p>
              <p>
                <strong>Policymaker:</strong> Elected official, regulator, or government appointee working on AI policy.
              </p>
              <p>
                <strong>Investor:</strong> VC partner, angel, or fund manager investing in AI companies.
              </p>
              <p>
                <strong>Organizer:</strong> Runs advocacy groups, coalitions, or grassroots efforts around AI.
              </p>
              <p>
                <strong>Journalist:</strong> Covers AI for a publication or media outlet.
              </p>
              <p>
                <strong>Academic:</strong> Professor or institutional researcher studying AI impacts, ethics, or
                governance.
              </p>
              <p>
                <strong>Cultural figure:</strong> Public intellectual, author, or artist shaping public discourse on AI.
              </p>
            </div>
          </details>

          <details className="mb-3 border border-[#e0e0e0] rounded">
            <summary className="px-3 py-2 font-mono text-[12px] font-medium cursor-pointer hover:bg-[#f5f5f5]">
              Organization categories
            </summary>
            <div className="px-3 pb-3 text-[13px] text-[#444] space-y-1">
              <p>
                <strong>Frontier Lab:</strong> Builds large-scale AI models (OpenAI, Anthropic, Google DeepMind, etc.).
              </p>
              <p>
                <strong>AI Safety/Alignment:</strong> Research orgs focused on making AI systems safe and aligned with
                human values.
              </p>
              <p>
                <strong>Think Tank/Policy Org:</strong> Produces policy research, white papers, and recommendations on
                AI governance.
              </p>
              <p>
                <strong>Government/Agency:</strong> Federal, state, or international government body with AI
                jurisdiction.
              </p>
              <p>
                <strong>Academic:</strong> University, research institute, or academic department.
              </p>
              <p>
                <strong>VC/Capital/Philanthropy:</strong> Funds AI companies or AI-related research through investment
                or grants.
              </p>
              <p>
                <strong>Labor/Civil Society:</strong> Unions, worker advocacy groups, or civil society organizations
                engaged with AI.
              </p>
              <p>
                <strong>Ethics/Bias/Rights:</strong> Focuses on algorithmic fairness, bias, civil rights, or ethical AI
                use.
              </p>
              <p>
                <strong>Media/Journalism:</strong> News outlet or publication covering AI.
              </p>
              <p>
                <strong>Political Campaign/PAC:</strong> Political campaign or committee taking positions on AI.
              </p>
              <p>
                <strong>Infrastructure & Compute:</strong> Provides chips, cloud compute, or infrastructure for AI
                development.
              </p>
              <p>
                <strong>Deployers & Platforms:</strong> Companies deploying AI in products or services at scale.
              </p>
            </div>
          </details>

          <details className="mb-3 border border-[#e0e0e0] rounded">
            <summary className="px-3 py-2 font-mono text-[12px] font-medium cursor-pointer hover:bg-[#f5f5f5]">
              Regulatory stance values
            </summary>
            <div className="px-3 pb-3 text-[13px] text-[#444] space-y-1">
              <p>
                <strong>Accelerate:</strong> Actively opposes regulation. Views restrictions as harmful to innovation.
              </p>
              <p>
                <strong>Light-touch:</strong> Prefers voluntary commitments and industry self-governance over binding
                rules.
              </p>
              <p>
                <strong>Moderate:</strong> Supports targeted regulation on specific risks while preserving room for
                development.
              </p>
              <p>
                <strong>Cautious:</strong> Favors comprehensive regulatory frameworks. Prioritizes safety over speed.
              </p>
              <p>
                <strong>Mixed/unclear:</strong> Positions are contradictory, context-dependent, or insufficiently
                documented.
              </p>
            </div>
          </details>

          <details className="mb-3 border border-[#e0e0e0] rounded">
            <summary className="px-3 py-2 font-mono text-[12px] font-medium cursor-pointer hover:bg-[#f5f5f5]">
              Edge (relationship) types
            </summary>
            <div className="px-3 pb-3 text-[13px] text-[#444] space-y-1">
              <p>
                <strong>employed_by:</strong> Works at the organization (current).
              </p>
              <p>
                <strong>founded:</strong> Founded or co-founded the organization.
              </p>
              <p>
                <strong>advises:</strong> Serves as an advisor.
              </p>
              <p>
                <strong>board_member:</strong> Sits on the board of directors.
              </p>
              <p>
                <strong>invested_in:</strong> Made a financial investment.
              </p>
              <p>
                <strong>funded_by:</strong> Receives funding from.
              </p>
              <p>
                <strong>subsidiary_of:</strong> Is a subsidiary or division of.
              </p>
              <p>
                <strong>partner_of:</strong> Formal partnership or collaboration.
              </p>
              <p>
                <strong>collaborator:</strong> Works together on specific projects.
              </p>
              <p>
                <strong>critic_of:</strong> Publicly critical of.
              </p>
              <p>
                <strong>supporter_of:</strong> Publicly supportive of.
              </p>
              <p>
                <strong>spun_out_from:</strong> Was created as a spinoff from.
              </p>
              <p>
                <strong>affiliated:</strong> General affiliation that doesn't fit other types.
              </p>
            </div>
          </details>

          <details className="mb-3 border border-[#e0e0e0] rounded">
            <summary className="px-3 py-2 font-mono text-[12px] font-medium cursor-pointer hover:bg-[#f5f5f5]">
              Funding model values
            </summary>
            <div className="px-3 pb-3 text-[13px] text-[#444] space-y-1">
              <p>
                <strong>Grants:</strong> Funded by philanthropic or government grants.
              </p>
              <p>
                <strong>Contracts:</strong> Funded by government or corporate contracts for specific work.
              </p>
              <p>
                <strong>VC:</strong> Venture capital funded.
              </p>
              <p>
                <strong>Donations:</strong> Funded by individual or organizational donations.
              </p>
              <p>
                <strong>Government:</strong> Government funded (appropriations, not grants).
              </p>
              <p>
                <strong>Revenue:</strong> Self-sustaining through product or service revenue.
              </p>
              <p>
                <strong>Endowment:</strong> Funded by an endowment.
              </p>
            </div>
          </details>
        </section>

        <section className={SECTION}>
          <h2 className={H2} style={{ fontFamily: "'EB Garamond', Georgia, serif" }}>
            Practical notes
          </h2>
          <ul className="list-disc pl-6 mb-3">
            <li className={LI}>All external links open in a new tab.</li>
            <li className={LI}>
              Use the "copy" button on citations, then Ctrl+F (Cmd+F on Mac) on the source page to search for the quote.
            </li>
            <li className={LI}>
              The timer tracks active time per entity. It pauses automatically after 2 minutes of inactivity, and you
              can pause/resume manually.
            </li>
            <li className={LI}>
              Corrections save immediately when submitted. Switching entities or closing the browser won't lose your
              work.
            </li>
            <li className={LI}>Click "Edit correction" on any previously flagged field to update it.</li>
            <li className={LI}>
              To see how the entity appears on the public map, visit{' '}
              <a
                href="https://mapping-ai.org/map"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-600 hover:underline"
              >
                mapping-ai.org/map
              </a>{' '}
              and search for it.
            </li>
            <li className={LI}>
              Congressional testimony, think tank reports, and organizational "about" pages tend to be reliable sources.
              Social media posts and news articles paraphrasing someone's views are less so.
            </li>
            <li className={LI}>
              Don't spend excessive time on entities where sources are all paywalled or dead. Mark those "Can't verify"
              and move on.
            </li>
          </ul>
        </section>

        <div className="text-center pb-8">
          <button
            onClick={onClose}
            className="font-mono text-[11px] uppercase tracking-wider px-6 py-2 rounded cursor-pointer border bg-[#1a1a1a] text-white border-[#1a1a1a] hover:bg-[#333] transition-colors"
          >
            Start Verifying
          </button>
        </div>
      </div>
    </div>
  )
}
