const SECTION = 'mb-8'
const H2 = 'text-xl mb-3'
const H3 = 'text-base font-medium mb-2 mt-4'
const P = 'text-[14px] text-[#333] leading-relaxed mb-3'
const LI = 'text-[14px] text-[#333] leading-relaxed mb-1.5'
const STEP = 'text-[14px] text-[#333] leading-relaxed mb-2 pl-4 border-l-2 border-[#ddd]'

export function MethodologyGuide({ onClose }: { onClose: () => void }) {
  return (
    <div className="fixed inset-0 z-50 bg-white overflow-y-auto">
      <div className="max-w-[750px] mx-auto px-6 py-8">
        <div className="flex items-center justify-between mb-8">
          <h1 className="text-2xl italic" style={{ fontFamily: "'EB Garamond', Georgia, serif" }}>
            Verification Guide
          </h1>
          <button
            onClick={onClose}
            className="font-mono text-[11px] uppercase tracking-wider px-3 py-1.5 rounded cursor-pointer border bg-white text-[#555] border-[#ccc] hover:border-[#999] transition-colors"
          >
            Close
          </button>
        </div>

        <section className={SECTION}>
          <h2 className={H2} style={{ fontFamily: "'EB Garamond', Georgia, serif" }}>
            Background
          </h2>
          <p className={P}>
            Mapping AI tracks people, organizations, and resources in the U.S. AI policy landscape. Most entity data was
            contributed by the public or generated by automated enrichment scripts. The automation is imperfect — some
            values are wrong, outdated, or missing. Verification means checking what's correct and flagging what isn't.
          </p>
        </section>

        <section className={SECTION}>
          <h2 className={H2} style={{ fontFamily: "'EB Garamond', Georgia, serif" }}>
            What to verify
          </h2>

          <h3 className={H3}>Structured fields</h3>
          <p className={P}>
            Basic facts: category, regulatory stance, AGI timeline belief, AI risk level, key concerns, funding model,
            website, title/role, primary organization, location. Each field has a value or shows "Not set." Check
            whether values look right. If a field is empty and you know the answer, flag it and provide the correct
            value.
          </p>

          <h3 className={H3}>Notes</h3>
          <p className={P}>
            Free-text summaries of an entity's positions, history, or relationships. May contain inaccuracies, outdated
            information, or unsupported assertions.
          </p>
        </section>

        <section className={SECTION}>
          <h2 className={H2} style={{ fontFamily: "'EB Garamond', Georgia, serif" }}>
            Workflow
          </h2>

          <h3 className={H3}>1. Pick an entity</h3>
          <p className={STEP}>
            The left sidebar lists entities by priority — those with fewest community votes appear first. Highly
            connected entities are prioritized because errors on them affect more of the map.
          </p>

          <h3 className={H3}>2. Review structured fields</h3>
          <p className={STEP}>
            Scan each field. Click "Flag" on anything wrong or missing — select the error type, enter the correct value
            if known, and add notes. Click "Set" if a field is empty and you know what it should be. Click "Can't
            verify" if you have no way to confirm or deny the value.
          </p>

          <h3 className={H3}>3. Review notes</h3>
          <p className={STEP}>
            Read through the notes section. Flag anything fabricated, inaccurate, or outdated. When flagging, explain
            what is wrong and what the correct information should be.
          </p>

          <h3 className={H3}>4. Mark complete</h3>
          <p className={STEP}>
            Click "Mark Complete" at the bottom. This records your review and the time spent. Corrections you flagged
            along the way are already saved. If you can't properly verify the entity (all sources paywalled, out of your
            domain), click "Can't verify" instead.
          </p>
        </section>

        <section className={SECTION}>
          <h2 className={H2} style={{ fontFamily: "'EB Garamond', Georgia, serif" }}>
            Error types
          </h2>

          <h3 className={H3}>Fields</h3>
          <ul className="list-disc pl-6 mb-3">
            <li className={LI}>
              <strong>Wrong value:</strong> Right field type, wrong specific value.
            </li>
            <li className={LI}>
              <strong>Outdated:</strong> Was correct but is no longer current.
            </li>
            <li className={LI}>
              <strong>Unsourced:</strong> Value cannot be verified from public sources.
            </li>
            <li className={LI}>
              <strong>Missing:</strong> Field is empty but a value exists and should be added.
            </li>
            <li className={LI}>
              <strong>Ambiguous:</strong> Value is technically correct but misleadingly vague.
            </li>
          </ul>

          <h3 className={H3}>Notes</h3>
          <ul className="list-disc pl-6 mb-3">
            <li className={LI}>
              <strong>Factual error:</strong> Contains incorrect facts or fabricated quotes.
            </li>
            <li className={LI}>
              <strong>Outdated:</strong> No longer current.
            </li>
            <li className={LI}>
              <strong>Biased framing:</strong> Accurate but framed in a misleading way.
            </li>
            <li className={LI}>
              <strong>Missing context:</strong> Omits information that changes the picture.
            </li>
          </ul>
        </section>

        <section className={SECTION}>
          <h2 className={H2} style={{ fontFamily: "'EB Garamond', Georgia, serif" }}>
            Reference: categories and field values
          </h2>
          <p className={P}>Click any section to expand definitions.</p>

          <details className="mb-3 border border-[#e0e0e0] rounded">
            <summary className="px-3 py-2 font-mono text-[12px] font-medium cursor-pointer hover:bg-[#f5f5f5]">
              Person categories
            </summary>
            <div className="px-3 pb-3 text-[13px] text-[#444] space-y-1">
              <p>
                <strong>Executive:</strong> CEO, CTO, VP, or equivalent leadership at an AI-relevant organization.
              </p>
              <p>
                <strong>Researcher:</strong> Publishes technical AI research, whether in industry or academia.
              </p>
              <p>
                <strong>Policymaker:</strong> Elected official, regulator, or government appointee working on AI policy.
              </p>
              <p>
                <strong>Investor:</strong> VC partner, angel, or fund manager investing in AI companies.
              </p>
              <p>
                <strong>Organizer:</strong> Runs advocacy groups, coalitions, or grassroots efforts around AI.
              </p>
              <p>
                <strong>Journalist:</strong> Covers AI for a publication or media outlet.
              </p>
              <p>
                <strong>Academic:</strong> Professor or institutional researcher studying AI impacts, ethics, or
                governance.
              </p>
              <p>
                <strong>Cultural figure:</strong> Public intellectual, author, or artist shaping public discourse on AI.
              </p>
            </div>
          </details>

          <details className="mb-3 border border-[#e0e0e0] rounded">
            <summary className="px-3 py-2 font-mono text-[12px] font-medium cursor-pointer hover:bg-[#f5f5f5]">
              Organization categories
            </summary>
            <div className="px-3 pb-3 text-[13px] text-[#444] space-y-1">
              <p>
                <strong>Frontier Lab:</strong> Builds large-scale AI models (OpenAI, Anthropic, Google DeepMind, etc.).
              </p>
              <p>
                <strong>AI Safety/Alignment:</strong> Research orgs focused on making AI systems safe and aligned.
              </p>
              <p>
                <strong>Think Tank/Policy Org:</strong> Produces policy research and recommendations on AI governance.
              </p>
              <p>
                <strong>Government/Agency:</strong> Federal, state, or international body with AI jurisdiction.
              </p>
              <p>
                <strong>Academic:</strong> University, research institute, or academic department.
              </p>
              <p>
                <strong>VC/Capital/Philanthropy:</strong> Invests in or funds AI companies and research.
              </p>
              <p>
                <strong>Labor/Civil Society:</strong> Workers' orgs, advocacy groups, community organizations.
              </p>
              <p>
                <strong>Ethics/Bias/Rights:</strong> Focuses on AI fairness, accountability, and civil rights.
              </p>
              <p>
                <strong>Media/Journalism:</strong> News organizations covering AI.
              </p>
              <p>
                <strong>Infrastructure & Compute:</strong> Cloud providers, chip makers, data center operators.
              </p>
              <p>
                <strong>Deployers & Platforms:</strong> Companies deploying AI in products and services.
              </p>
            </div>
          </details>

          <details className="mb-3 border border-[#e0e0e0] rounded">
            <summary className="px-3 py-2 font-mono text-[12px] font-medium cursor-pointer hover:bg-[#f5f5f5]">
              Regulatory stance values
            </summary>
            <div className="px-3 pb-3 text-[13px] text-[#444] space-y-1">
              <p>
                <strong>Accelerate:</strong> Opposes most regulation; favors rapid, unrestricted development.
              </p>
              <p>
                <strong>Light-touch:</strong> Favors voluntary guidelines over binding rules.
              </p>
              <p>
                <strong>Moderate:</strong> Supports targeted regulation for high-risk use cases.
              </p>
              <p>
                <strong>Cautious:</strong> Favors broad regulatory frameworks and slower deployment.
              </p>
              <p>
                <strong>Mixed/unclear:</strong> Positions are inconsistent or insufficiently documented.
              </p>
            </div>
          </details>

          <details className="mb-3 border border-[#e0e0e0] rounded">
            <summary className="px-3 py-2 font-mono text-[12px] font-medium cursor-pointer hover:bg-[#f5f5f5]">
              Practical tips
            </summary>
            <div className="px-3 pb-3 text-[13px] text-[#444] space-y-2">
              <p>Search the entity's name + "AI" on the web to find recent statements.</p>
              <p>Wikipedia and LinkedIn are useful for category, title, and org fields.</p>
              <p>For regulatory stance: look for public statements, testimony, op-eds, or funding patterns.</p>
              <p>If you're unsure about a field, use "Can't verify" rather than guessing.</p>
              <p>The timer pauses after 2 minutes of inactivity — resume it when you return to the review.</p>
            </div>
          </details>
        </section>
      </div>
    </div>
  )
}
